### ISSUE TITLE
packet id and timestamp order

### ISSUE THREAD

**Issue by fkerem** [iot-lab/aggregation-tools#17]
I don't know whether this is really a problem but timestamps are not increasing always when I sort the data with respect to the packet IDs. I believe this can happen because of the time sync. in the nodes or the control nodes. It depends on the aggregation strategy and this seems not to be unexpected.

<img width="1200" alt="image" src="https://user-images.githubusercontent.com/25817120/114635277-0e796e80-9ccd-11eb-8414-de3d9ccefeae.png">

<img width="1203" alt="image" src="https://user-images.githubusercontent.com/25817120/114635441-6912ca80-9ccd-11eb-9946-070163e0776c.png">

Wanted to ask, just in case. Appreciate your help.

**Comment by fsaintma** [comment]
Hi @fkerem ,
Just to understand, have you just one node in sniffer mode (monitoring profile) in your experiment and Wireshark trace ?
Thanks.

**Comment by fkerem** [comment]
Hi @fsaintma,
Sorry, I forgot to mention it. I use 1 BR node and 3 http-example nodes. I added sniffers to all of them.
Thanks!
