### ISSUE TITLE
Duplicate packets as many as the number of nodes with the sniffer profile attached

### ISSUE THREAD

**Issue by fkerem** [iot-lab/aggregation-tools#21]
Hi,

Even though the destination or source address in a packet does not belong to all of the nodes that I experiment with, the pcap contains its duplicates as many as the number of nodes with the sniffer profile attached.

Example:

I use sniffers for 27 nodes and get the UDP packets below exactly 27 times:

<img width="931" alt="image" src="https://user-images.githubusercontent.com/25817120/122818861-60003400-d2e2-11eb-8af6-8f2b3a312a13.png">

The issue can be observed with other types of packets as well:

<img width="1063" alt="image" src="https://user-images.githubusercontent.com/25817120/122819025-8e7e0f00-d2e2-11eb-98f8-8dd42f812196.png">

What can be the reason or issue?

Best,

**Comment by fsaintma** [comment]
Hi @fkerem 
I don't understand your question. If you have 27 nodes with a sniffer profile attached it could be normal to see 27 times a packet. Indeed all sniffer nodes capture the radio traffic independently and probably they capture the same packet. So in sniffer aggregator you see the packet for each sniffer.
I may not have understood anything :)

**Comment by fkerem** [comment]
Hi @fsaintma
I think, you got my question. However, here, the packet addresses just belong to 2 nodes (the source and destination), why the others capture it even though the packet was not sent or received by them?
Best,

**Comment by fsaintma** [comment]
@fkerem because a sniffer capture ALL radio traffic by default. It does not take into account the source and destination. So it is not necessary to have one sniffer per node to capture the radio traffic of a sensors network. It can be useful to have several sniffers if the nodes are not in the same radio neighborhood.

**Comment by fkerem** [comment]
I got it @fsaintma , thank you very much for the info. I'll try to handle it by preprocessing the data somehow then.

**Comment by fkerem** [comment]
Hi @fsaintma 

I would like to ask whether the sniffers are also affected by other experiments of mine or other users when I run the aggregator targeted at a specific experiment?
Is there a filtering mechanism there?

Best,

**Comment by fsaintma** [comment]
Hi,
Yes you are affected by other experiments which do radio traffic on the same channel. So it could be a problem even more of TSCH with the use of several channels. On Grenoble site you can book a lot of nodes (building wing) to ensure that a set of your nodes can't communicate with other experiments nodes. But be careful I didn't resolve the problem of malformed packets sended by an unknown source.
Best

**Comment by fkerem** [comment]
OK then, I'll first try to preprocess the pcap files to ensure the captured traffic belongs to the nodes in my experiment.
If I need, I'll try what you have suggested in Grenoble site. Thank you so much @fsaintma.
